---

# Debian install tasks

- name: 'INSTALL | APT | Install openjdk-jre packages'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: "{{ openjdk_jre_apt_update_cache }}"
    cache_valid_time: "{{ openjdk_jre_apt_cache_valid_time | default(omit) }}"
  with_items: "{{ openjdk_jre_packages }}"
