---

# Main tasks file for openjdk-jre role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::openjdk-jre'
    - 'role::openjdk-jre::install'


- name: 'INSTALL | Manage installation tasks for your OS family'
  become: True
  include: "{{ role_path }}/tasks/install_{{ ansible_os_family | lower }}.yml"
  tags:
    - 'role::openjdk-jre'
    - 'role::openjdk-jre::install'
